image: beevelop/ionic:latest
pages:
  stage: deploy
  script:
  - npm install
  - ionic cordova build browser
  - mkdir .public
  - cp -R www/* .public
  - mv .public public
  artifacts:
    paths:
    - public/
  only:
  - dev